{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  labels:
    eonkube: airbytechart
    {{- include "minio.standard.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}

{{- end }}
