apiVersion: v1
kind: ConfigMap
metadata:
  name: airbyte-db-check-cm
  namespace: {{ .Release.Namespace }}
  labels:
    eonkube: airbytechart
    {{ include "airbyte.databaseLabels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  wait-db.sh: |
    {{- include (print $.Template.BasePath "/db-check/_wait-for-db.sh") . | nindent 4 }}
  wait-db-bootloader.sh: |
    {{- include (print $.Template.BasePath "/db-check/_wait-for-db-bootloader.sh") . | nindent 4 }}