apiVersion: v2
appVersion: 0.40.3
dependencies:
- name: common
  repository: '@infortrend'
  tags:
  - bitnami-common
  version: 2.2.4
deprecated: true
description: Helm chart to deploy airbyte-metrics
name: metrics
type: application
version: 0.45.12
