{{- if eq .Values.mode "distributed" }}
{{ $scheme := or .Values.tls.enabled .Values.selfsigned.enabled | ternary "https" "http" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "minio.fullname" . }}-svc
  labels: 
    eonkube: airbytechart
    {{- include "minio.standard.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: {{ $scheme }}
      port: {{ .Values.api.service.port }}
      protocol: TCP
      targetPort: {{ .Values.minioAPIPort }}
  selector:
    {{- include "minio.selector.labels" . | nindent 4 }}
{{- end }}