{{- $api_tls := and .Values.api.ingress.enabled .Values.api.ingress.tls.defaultSelfSignedCert -}}
{{- $console_tls := and .Values.console.ingress.enabled .Values.console.ingress.tls.defaultSelfSignedCert -}}
{{- if or .Values.selfsigned.enabled $api_tls $console_tls }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "minio.fullname" . }}-selfsigned-cm
  namespace: {{ .Release.Namespace }}
  labels:
    eonkube: airbytechart
    {{- include "minio.standard.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"

data:
  
  selfsigned-issuer.yaml: |
    {{- include (print $.Template.BasePath "/self-signed-cert/_selfSigned-issuer.yaml") . | nindent 4 }}
  selfsigned-certificate.yaml: |
    {{- include (print $.Template.BasePath "/self-signed-cert/_selfSigned-certificate.yaml") . | nindent 4 }}
  {{- if .Values.selfsigned.enabled }}
  selfsigned-tls.yaml: |
    {{- include (print $.Template.BasePath "/self-signed-cert/_selfSigned-tls.yaml") . | nindent 4 }}
  {{- end }}
  tls-issuer.yaml: |
    {{- include (print $.Template.BasePath "/self-signed-cert/_tls-issuer.yaml") . | nindent 4 }}
  
{{- end }}