---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-airbyte-webapp-svc
  annotations:
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{ if and .Values.service.vipSharingEnabled .Values.service.loadbalancerip }}metallb.universe.tf/allow-shared-ip: {{ printf "key-to-share-%s" .Values.service.loadbalancerip | quote }}{{ end }}
    {{ if .Values.service.dnsEnabled }}external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname | quote }}{{ end }}
  labels:
    eonkube: airbytechart
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" }}loadBalancerIP: {{ .Values.service.loadbalancerip  }}{{ end }}
  ports:
  - port: {{ .Values.service.port }}
    {{ if eq .Values.service.type "NodePort" }}nodePort: {{ .Values.service.nodePort }}{{ end }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    {{- if .Values.extraSelectorLabels }}
    {{ toYaml (mergeOverwrite .Values.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 4 }}
    {{- end }}
